### ISSUE TITLE
TheIntelHub Feed doesn't convert to RSS or Atom

### ISSUE THREAD

**Issue by immabefree** [HBehrens/feedsanitizer#10]
url: http://theintelhub.com/feed/rss/
format: rss
Traceback (most recent call last):
  File "/base/data/home/apps/feedsanitizer/1.353467691866276609/views.py", line 82, in userfriendly
    feed = buildfeed(url, feed_class, feed_link, ids)
  File "/base/data/home/apps/feedsanitizer/1.353467691866276609/views.py", line 31, in buildfeed
    updated = datetimefromparsed(entry.updated_parsed)
  File "/base/data/home/apps/feedsanitizer/1.353467691866276609/feedparser.py", line 356, in **getattr**
    raise AttributeError, "object has no attribute '%s'" % key
AttributeError: object has no attribute 'updated_parsed'

**Comment by HBehrens** [comment]
closed with 2a2ee178c56997b8360272839b7347eeefa9e658
