### ISSUE TITLE
"Oops" on http://u3d.as/feed/latest.rss

### ISSUE THREAD

**Issue by tabascoterrier** [HBehrens/feedsanitizer#14]
When trying to sanitize http://u3d.as/feed/latest.rss

I'm seeing a trackback:

url: http://u3d.as/feed/latest.rss
format: rss
Traceback (most recent call last):
  File "/base/data/home/apps/feedsanitizer/1.353769649187310229/views.py", line 83, in userfriendly
    feed = buildfeed(url, feed_class, feed_link, ids)
  File "/base/data/home/apps/feedsanitizer/1.353769649187310229/views.py", line 32, in buildfeed
    entry_link =  entry.link if "link" in entry else entry.links[0]["href"]
  File "/base/data/home/apps/feedsanitizer/1.353769649187310229/feedparser.py", line 356, in **getattr**
    raise AttributeError, "object has no attribute '%s'" % key
AttributeError: object has no attribute 'links'

http://feedsanitizer.appspot.com/?url=http%3A%2F%2Fu3d.as%2Ffeed%2Flatest.rss&format=rss

**Comment by tabascoterrier** [comment]
The feed source was:

<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/xsl/rss.xsl"?>

<rss version="2.0"
 xmlns:blogChannel="http://backend.userland.com/blogChannelModule"


<channel>
<title>Unity Asset Store newest packages</title>
<link>http://www.unity3d.com/</link>
<description>The newest packages in the Unity Asset Store.</description>
<language>en-us</language>
<copyright>Unity Technologies</copyright>
<pubDate>Tue, 15 Jan 2013 20:38:49 -0000</pubDate>
<ttl>60</ttl>

<image>
<title>Unity</title>
<url>http://download.unity3d.com/images/news/unity-logo.png</url>
<link>http://www.unity3d.com/</link>
</image>
<item>
<title>Seamless Textures 6-Pack by Broken Toy Games</title>
<link>http://u3d.as/3q2</link>
<description>&#x3C;a href=&#x22;http://u3d.as/3q2&#x22;&#x3E;&#x3C;img vspace=&#x22;4&#x22; border=&#x22;1&#x22; hspace=&#x22;4&#x22; align=&#x22;left&#x22; alt=&#x22;&#x22; src=&#x22;//d2ujflorbtfzji.cloudfront.net/key-image/0a51099a-5f13-4759-ae3f-ec85f57b4860.jpg&#x22; /&#x3E;&#x3C;/a&#x3E;Add character to your scenes with this pack of six quality seamless tiling textures for terrain. &#x3C;br&#x3E;&#x3C;br&#x3E;Optimized for games. Comes with normal maps and hand-made alpha layers for advanced effects. &#x3C;br&#x3E;&#x3C;br&#x3E;Included for free in the Triplanar Projection Shaders asset, available &#x3C;a href=http://u3d.as/content/broken-toy-games/triplanar-texturing/1Ds&#x3E; here&#x3C;/a&#x3E;.&#x3C;br/&#x3E;&#x3C;span class=&#x22;price&#x22;&#x3E;&#x3C;strong&#x3E;Price $5.00&#x3C;/strong&#x3E;&#x3C;/span&#x3E;</description>
<category>Textures &#x26; Materials</category>
<guid isPermaLink="false">4524</guid>
<pubDate>Tue, 15 Jan 2013 20:37:05 -0000</pubDate>
</item>
<item>
<title>FPS Guns 12 Pack by piccolo</title>
<description>&#x3C;a href=&#x22;&#x22;&#x3E;&#x3C;img vspace=&#x22;4&#x22; border=&#x22;1&#x22; hspace=&#x22;4&#x22; align=&#x22;left&#x22; alt=&#x22;&#x22; src=&#x22;//d2ujflorbtfzji.cloudfront.net/key-image/6ab704f5-7085-41ee-ac02-c03be7c00a06.png&#x22; /&#x3E;&#x3C;/a&#x3E;This pack includes 12 weapons. &#x3C;br&#x3E;&#x3C;br&#x3E; - Weapon textures are 512. &#x3C;br&#x3E;&#x3C;br&#x3E; - Weapons&#x27; tris count &#x3C;Br&#x3E;&#x3C;br&#x3E; [ M79 : 1038] &#x3C;br&#x3E;&#x3C;br&#x3E; [ AT4 : 602] &#x3C;Br&#x3E;&#x3C;br&#x3E; [ Carbine : 997] &#x3C;br&#x3E;&#x3C;br&#x3E; [ DBS : 712] &#x3C;br&#x3E;&#x3C;br&#x3E; [ M16 : 997] &#x3C;br&#x3E;&#x3C;br&#x3E; [ Grenade04 : 985] &#x3C;br&#x3E;&#x3C;br&#x3E; [ M32 : 996] &#x3C;br&#x3E;&#x3C;br&#x3E; [ M202 : 813] &#x3C;br&#x3E;&#x3C;br&#x3E; [ MG4 : 1000] &#x3C;br&#x3E;&#x3C;br&#x3E; [ Rocket : 846] &#x3C;br&#x3E;&#x3C;br&#x3E; [ Sniper : 1090] &#x3C;br&#x3E;&#x3C;br&#x3E; [Vulcan : 965] &#x3C;br/&#x3E;&#x3C;span class=&#x22;price&#x22;&#x3E;&#x3C;strong&#x3E;Price $60.00&#x3C;/strong&#x3E;&#x3C;/span&#x3E;</description>
<category>3D Models/Props/Weapons/Guns</category>
<guid isPermaLink="false">6431</guid>
<pubDate>Tue, 15 Jan 2013 20:27:25 -0000</pubDate>
</item>
<item>
<title>Dungeon Builder Starter Kit by BITGEM</title>
<link>http://u3d.as/3rH</link>
<description>&#x3C;a href=&#x22;http://u3d.as/3rH&#x22;&#x3E;&#x3C;img vspace=&#x22;4&#x22; border=&#x22;1&#x22; hspace=&#x22;4&#x22; align=&#x22;left&#x22; alt=&#x22;&#x22; src=&#x22;//d2ujflorbtfzji.cloudfront.net/key-image/56bd9f5a-ec19-4abe-bb88-c807bbf72365.jpg&#x22; /&#x3E;&#x3C;/a&#x3E;30+ Assets to give you a quick start in building your own dungeon. For best results we highly recommend the &#x3C;a href=&#x22;http://u3d.as/content/pl-young/uni-rpg-tile-ed/3gL&#x22;&#x3E;UniRPG tile editor extension&#x3C;/a&#x3E; which will fast track building your dungeon scenes, no endless vertex snapping all those wall, just paint the dungeon you want with a few mouse clicks!&#x3C;br&#x3E;&#x3C;br&#x3E; Update v2.0 (please backup your old projects)&#x3C;br&#x3E; - Mobile optimized version of core assets (6303 tris down to 2079)&#x3C;br&#x3E; - 1 Atlas texure to reduce drawcalls on main assets (1024 and 4096 are supplied)&#x3C;br&#x3E; - Draw calls reduced by 50% - 80% since v1.0&#x3C;br&#x3E; &#x3C;br&#x3E; Set Includes &#x3C;br&#x3E; - Large Archway&#x3C;br&#x3E; - 6 Wall Sections&#x3C;br&#x3E; - 3 Wall Corners&#x3C;br&#x3E; - 5 Foor Titles&#x3C;br&#x3E; - 3 Stone Floor Dividers&#x3C;br&#x3E; - 1 Pit&#x3C;br&#x3E; - 2 Candles/Arrangement&#x3C;br&#x3E; - 2 Firepits&#x3C;br&#x3E; - 1 Plinth&#x3C;br&#x3E; - 2 Wall Torches&#x3C;br&#x3E; - Doors/Gates (2 variations each + archway version)&#x3C;br&#x3E; - 1 Small Animated Chest (3 Treasure Types)&#x3C;br&#x3E; - 3 Vases&#x3C;br&#x3E;&#x3C;br&#x3E; Don&#x27;t forget to check out the rest of &#x3C;a href=&#x22;http://u3d.as/publisher/bitgem/2S0&#x22;&#x3E;our collection&#x3C;/a&#x3E; which contains heaps of dungeon ready assets with plenty more on the way.&#x3C;br&#x3E;&#x3C;br&#x3E;&#x3C;br/&#x3E;&#x3C;span class=&#x22;price&#x22;&#x3E;&#x3C;strong&#x3E;Price $50.00&#x3C;/strong&#x3E;&#x3C;/span&#x3E;</description>
<category>3D Models/Environments/Dungeons</category>
<guid isPermaLink="false">4590</guid>
<pubDate>Tue, 15 Jan 2013 20:18:25 -0000</pubDate>
</item>
<item>
<title>Dungeon Construction Kit by NeoPax</title>
<link>http://u3d.as/1tL</link>
<description>&#x3C;a href=&#x22;http://u3d.as/1tL&#x22;&#x3E;&#x3C;img vspace=&#x22;4&#x22; border=&#x22;1&#x22; hspace=&#x22;4&#x22; align=&#x22;left&#x22; alt=&#x22;&#x22; src=&#x22;//d2ujflorbtfzji.cloudfront.net/key-image/265824A6-8333-11E0-B7C7-BFF51496DD27.png&#x22; /&#x3E;&#x3C;/a&#x3E;This is a gothic dungeon construction kit. A set of pieces which fit each other textures (color, specular, normal) source files (fbx) bonus of additional props and effects (torch light, fireball, barrel and so on) DCK will be constantly updated - all updates are free for our customers!&#x3C;br /&#x3E;&#x3C;br /&#x3E; &#x3C;a href=&#x22;http://www.kolbasoff.com/game2/&#x22;&#x3E; ONLINE DEMO HERE &#x3C;/a&#x3E;&#x3C;br/&#x3E;&#x3C;span class=&#x22;price&#x22;&#x3E;&#x3C;strong&#x3E;Price $75.00&#x3C;/strong&#x3E;&#x3C;/span&#x3E;</description>
<category>3D Models/Environments/Dungeons</category>
<guid isPermaLink="false">179</guid>
<pubDate>Tue, 15 Jan 2013 20:12:31 -0000</pubDate>
</item>
<item>
<title>Cool Robot pack 01 by frogrice</title>
<link>http://u3d.as/3Xi</link>
<description>&#x3C;a href=&#x22;http://u3d.as/3Xi&#x22;&#x3E;&#x3C;img vspace=&#x22;4&#x22; border=&#x22;1&#x22; hspace=&#x22;4&#x22; align=&#x22;left&#x22; alt=&#x22;&#x22; src=&#x22;//d2ujflorbtfzji.cloudfront.net/key-image/7a5c0455-b9f3-4fea-a7ad-9cf36fde3e28.png&#x22; /&#x3E;&#x3C;/a&#x3E;This is Cool Robot pack 01. This pack includes 2 cool robots, and models are lowpoly.&#x3C;br/&#x3E;&#x3C;span class=&#x22;price&#x22;&#x3E;&#x3C;strong&#x3E;Price $5.00&#x3C;/strong&#x3E;&#x3C;/span&#x3E;</description>
<category>3D Models/Characters/Robots</category>
<guid isPermaLink="false">6427</guid>
<pubDate>Tue, 15 Jan 2013 20:03:46 -0000</pubDate>
</item>
<item>
<title>Orthello 2D Framework by WyrmTale Games</title>
<link>http://u3d.as/1Z9</link>
<description>&#x3C;a href=&#x22;http://u3d.as/1Z9&#x22;&#x3E;&#x3C;img vspace=&#x22;4&#x22; border=&#x22;1&#x22; hspace=&#x22;4&#x22; align=&#x22;left&#x22; alt=&#x22;&#x22; src=&#x22;//d2ujflorbtfzji.cloudfront.net/key-image/2feb1241-6002-4eac-aa29-b68fb2dd11a7.png&#x22; /&#x3E;&#x3C;/a&#x3E;| &#x3C;a href=&#x22;http://www.wyrmtale.com/orthello&#x22;&#x3E;&#x3C;strong&#x3E;User Guide&#x3C;/strong&#x3E;&#x3C;/a&#x3E; | &#x3C;a href=&#x22;http://www.wyrmtale.com/products/unity3d-components/orthello&#x22;&#x3E;&#x3C;strong&#x3E;Online Demo&#x3C;/strong&#x3E;&#x3C;/a&#x3E; | &#x3C;a href=&#x22;http://www.wyrmtale.com/ref/orthello/&#x22;&#x3E; &#x3C;strong&#x3E;API Reference&#x3C;/strong&#x3E;&#x3C;/a&#x3E; |&#x3C;br&#x3E;&#x3C;br&#x3E; &#x3C;strong&#x3E;Create your 2D applications and games&#x3C;/strong&#x3E;. &#x3C;br&#x3E; - 2D Development Framework: create sprites, use sprite sheets and play animations.&#x3C;br&#x3E; - 2D side / top-down / 2.5D / 3D integration (UI).&#x3C;br&#x3E; - Drag and drop, physics, sound support.&#x3C;br&#x3E; - Dynamic batching through material caching.&#x3C;br&#x3E; - View zoom, auto scale, pixel perfect and follow target and much more....&#x3C;br&#x3E; &#x3C;br&#x3E; &#x3C;strong&#x3E;C# and Javascript code integration&#x3C;/strong&#x3E;. &#x3C;br&#x3E; Multiple examples (C# + Javascript ), with inline documentation, are included for learning purposes.&#x3C;br&#x3E;&#x3C;br/&#x3E;&#x3C;span class=&#x22;price&#x22;&#x3E;&#x3C;strong&#x3E;FREE DOWNLOAD&#x3C;/strong&#x3E;&#x3C;/span&#x3E;</description>
<category>Scripting</category>
<guid isPermaLink="false">1014</guid>
<pubDate>Tue, 15 Jan 2013 20:03:32 -0000</pubDate>
</item>
<item>
<title>Barrel Pack by Digital Forest</title>
<link>http://u3d.as/3t8</link>
<description>&#x3C;a href=&#x22;http://u3d.as/3t8&#x22;&#x3E;&#x3C;img vspace=&#x22;4&#x22; border=&#x22;1&#x22; hspace=&#x22;4&#x22; align=&#x22;left&#x22; alt=&#x22;&#x22; src=&#x22;//d2ujflorbtfzji.cloudfront.net/key-image/303df635-67d2-4d33-bb29-df316c8df572.png&#x22; /&#x3E;&#x3C;/a&#x3E;&#x3C;strong&#x3E;Barrel pack&#x3C;/strong&#x3E; &#x3C;br&#x3E; &#x3C;br&#x3E;\- All the barrels you will need for your game. &#x3C;br&#x3E;\- Optimised models without losing detail, for optimal performance. &#x3C;br&#x3E;\- High quality 1024x1024 textures. &#x3C;br&#x3E;\- All prefabs include colliders and rigidbodies, ready for action! &#x3C;br&#x3E; &#x3C;br&#x3E;This package contains: &#x3C;br&#x3E;\- Over 40 prefabs &#x3C;br&#x3E;\- More than 30 Materials, some of which can be changed into any color &#x3C;br&#x3E;\- Over 50 unique Textures, including Normal and Specular maps&#x3C;br&#x3E;&#x3C;br&#x3E;&#x3C;br/&#x3E;&#x3C;span class=&#x22;price&#x22;&#x3E;&#x3C;strong&#x3E;Price $5.00&#x3C;/strong&#x3E;&#x3C;/span&#x3E;</description>
<category>3D Models/Props</category>
<guid isPermaLink="false">4711</guid>
<pubDate>Tue, 15 Jan 2013 20:00:09 -0000</pubDate>
</item>
<item>
<title>High- and low poly tires and wheels by TioMau</title>
<link>http://u3d.as/3Xh</link>
<description>&#x3C;a href=&#x22;http://u3d.as/3Xh&#x22;&#x3E;&#x3C;img vspace=&#x22;4&#x22; border=&#x22;1&#x22; hspace=&#x22;4&#x22; align=&#x22;left&#x22; alt=&#x22;&#x22; src=&#x22;//d2ujflorbtfzji.cloudfront.net/key-image/ce0ff9aa-2c64-4609-b939-5ee75ae50c43.png&#x22; /&#x3E;&#x3C;/a&#x3E;High- and low poly tires and wheels.&#x3C;br&#x3E;&#x3C;br&#x3E; This package includes seven high poly tires and seven low poly tires.&#x3C;br&#x3E;&#x3C;br&#x3E; Check out the demo on our website:&#x3C;br&#x3E; &#x3C;a href=&#x22;http://www.unitypolygons.com/tires/tires.html&#x22;&#x3E; Click here &#x3C;/a&#x3E; &#x3C;br/&#x3E;&#x3C;span class=&#x22;price&#x22;&#x3E;&#x3C;strong&#x3E;Price $5.00&#x3C;/strong&#x3E;&#x3C;/span&#x3E;</description>
<category>3D Models/Vehicles/Land</category>
<guid isPermaLink="false">6386</guid>
<pubDate>Tue, 15 Jan 2013 19:50:06 -0000</pubDate>
</item>
<item>
<title>Villager B Boy by CrossRoad_kimys2848</title>
<link>http://u3d.as/3Pw</link>
<description>&#x3C;a href=&#x22;http://u3d.as/3Pw&#x22;&#x3E;&#x3C;img vspace=&#x22;4&#x22; border=&#x22;1&#x22; hspace=&#x22;4&#x22; align=&#x22;left&#x22; alt=&#x22;&#x22; src=&#x22;//d2ujflorbtfzji.cloudfront.net/key-image/a32a36a2-11e4-492a-a4a8-a69a7d187e95.png&#x22; /&#x3E;&#x3C;/a&#x3E;This model has no alphamap and It has 13 animations.&#x3C;br&#x3E;&#x3C;br&#x3E; &#x3E;Idle&#x3C;br&#x3E; &#x3E;Greeting&#x3C;br&#x3E; &#x3E;Talk&#x3C;br&#x3E; &#x3E;Walk&#x3C;br&#x3E; &#x3E;Run&#x3C;br&#x3E; &#x3E;Jump&#x3C;br&#x3E; &#x3E;ATK_Standy&#x3C;br&#x3E; &#x3E;Attack01&#x3C;br&#x3E; &#x3E;Attack02&#x3C;br&#x3E; &#x3E;Damage&#x3C;br&#x3E; &#x3E;Death&#x3C;br&#x3E; &#x3E;&#x3C;strong&#x3E;[Elevator]&#x3C;/strong&#x3E;&#x3C;br&#x3E; &#x3E;&#x3C;strong&#x3E;[GangnamStyle]&#x3C;/strong&#x3E;&#x3C;br&#x3E;&#x3C;br&#x3E; Visit my site for more info&#x3C;br&#x3E;&#x3C;br&#x3E; &#x3C;a href=&#x22;http://blog.naver.com/kimys2848/173683050&#x22;&#x3E;[My Blog]&#x3C;/a&#x3E;&#x3C;br&#x3E; &#x3C;a href=&#x22;http://kimys2848.nayana.com/npc/bvillarger/villargerb.html&#x22;&#x3E;[Demo scene]&#x3C;/a&#x3E; &#x3C;br&#x3E;&#x3C;br&#x3E; &#x3C;br/&#x3E;&#x3C;span class=&#x22;price&#x22;&#x3E;&#x3C;strong&#x3E;Price $10.00&#x3C;/strong&#x3E;&#x3C;/span&#x3E;</description>
<category>3D Models/Characters/Toons</category>
<guid isPermaLink="false">5983</guid>
<pubDate>Tue, 15 Jan 2013 19:49:23 -0000</pubDate>
</item>
<item>
<title>Transition Toolkit by shallway</title>
<link>http://u3d.as/3Q9</link>
<description>&#x3C;a href=&#x22;http://u3d.as/3Q9&#x22;&#x3E;&#x3C;img vspace=&#x22;4&#x22; border=&#x22;1&#x22; hspace=&#x22;4&#x22; align=&#x22;left&#x22; alt=&#x22;&#x22; src=&#x22;//d2ujflorbtfzji.cloudfront.net/key-image/2769edb2-bf44-41e1-9bf2-8ce874ccbc4f.png&#x22; /&#x3E;&#x3C;/a&#x3E;&#x3C;strong&#x3E;\- This asset requires Unity Pro - &#x3C;/strong&#x3E; &#x3C;br&#x3E;&#x3C;br&#x3E; Transition Toolkit is an easy solution to make custom transition effects. &#x3C;br&#x3E; &#x3C;br&#x3E; &#x3C;a href=&#x22;http://shallway.net/products/transitiontoolkit/WebPlayer.html&#x22;&#x3E;WebPlayer&#x3C;/a&#x3E; &#x3C;br&#x3E; &#x3C;br&#x3E; &#x3C;strong&#x3E;Features&#x3C;/strong&#x3E; &#x3C;br&#x3E;\* Full Inspector integration. &#x3C;br&#x3E;\* Supports mobile device. &#x3C;br&#x3E;\* Suitable for both 3D and 2D games. &#x3C;br&#x3E;\* Very simple to use. &#x3C;br&#x3E;\* 30 preset transition effects are included. &#x3C;br&#x3E; &#x3C;br&#x3E;Visit the &#x3C;a href=&#x22;http://forum.unity3d.com/threads/163007-TransitionToolkit-Simple-tool-to-make-transition-effects&#x22;&#x3E;forum thread&#x3C;/a&#x3E; for more information.&#x3C;br&#x3E;&#x3C;br&#x3E;&#x3C;br/&#x3E;&#x3C;span class=&#x22;price&#x22;&#x3E;&#x3C;strong&#x3E;Price $20.00&#x3C;/strong&#x3E;&#x3C;/span&#x3E;</description>
<category>Scripting/Effects</category>
<guid isPermaLink="false">5992</guid>
<pubDate>Tue, 15 Jan 2013 19:46:09 -0000</pubDate>
</item>
</channel>
</rss>
