### ISSUE TITLE
Oops on http://www.brainfeedersite.com/feed/

### ISSUE THREAD

**Issue by kkkrist** [HBehrens/feedsanitizer#15]
url: http://www.brainfeedersite.com/feed/
format: rss
Traceback (most recent call last):
  File "/base/data/home/apps/feedsanitizer/1.353769649187310229/views.py", line 86, in userfriendly
    prettyxml = xml.dom.minidom.parseString(feedxml.getvalue()).toprettyxml()
  File "/base/python_runtime/python_dist/lib/python2.5/xml/dom/minidom.py", line 1923, in parseString
    return expatbuilder.parseString(string)
  File "/base/python_runtime/python_dist/lib/python2.5/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/base/python_runtime/python_dist/lib/python2.5/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
ExpatError: not well-formed (invalid token): line 57, column 45

Thanks!

**Comment by kkkrist** [comment]
(cleaning up old issues)
