### ISSUE TITLE
Feed sanitizer error

### ISSUE THREAD

**Issue by EasyRiderOnTheStorm** [HBehrens/feedsanitizer#7]
url: http://www.samandfuzzy.com/rss.php
format: rss
Traceback (most recent call last):
  File "/base/data/home/apps/feedsanitizer/1.349123672774720160/views.py", line 70, in userfriendly
    feed = buildfeed(url, feed_class, feed_link, ids)
  File "/base/data/home/apps/feedsanitizer/1.349123672774720160/views.py", line 31, in buildfeed
    id = "http://feedsanitizer.appspot.com/id/%s" % (urllib.quote_plus(entry.id))
  File "/base/data/home/apps/feedsanitizer/1.349123672774720160/feedparser.py", line 356, in **getattr**
    raise AttributeError, "object has no attribute '%s'" % key
AttributeError: object has no attribute 'id'

**Comment by HBehrens** [comment]
Thank you for your feedback. The updated version is now [up and running](http://feedsanitizer.appspot.com/?url=http%3A%2F%2Fwww.samandfuzzy.com%2Frss.php&format=rss). Could you verify the result, please?

**Comment by EasyRiderOnTheStorm** [comment]
Thank you. It works fine now.
