### ISSUE TITLE
Trunews rss xml not importing

### ISSUE THREAD

**Issue by immabefree** [HBehrens/feedsanitizer#8]
url: http://www.trunews.com/listen_now_podcast_feed.xml
format: rss
Traceback (most recent call last):
  File "/base/data/home/apps/feedsanitizer/1.352729602152509413/views.py", line 71, in userfriendly
    feed = buildfeed(url, feed_class, feed_link, ids)
  File "/base/data/home/apps/feedsanitizer/1.352729602152509413/views.py", line 31, in buildfeed
    idish = entry.id if "id" in entry else fixurl(entry.link)
  File "/base/data/home/apps/feedsanitizer/1.352729602152509413/feedparser.py", line 356, in **getattr**
    raise AttributeError, "object has no attribute '%s'" % key
AttributeError: object has no attribute 'link'

**Comment by HBehrens** [comment]
Thanks for filing this issue, it should be fixed by now. Could you please double check and re-open this issue if you find anything else?

**Comment by immabefree** [comment]
Fixed, but still doesn't work my purposes as I have to post it through Facebook. I think the xml feed is gimped. I'll probably end up just using dlvr.it for my purposes. Thanks.
